language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
before_install:
  - npm install -g npm@$NPM_VERSION
env:
  - NPM_VERSION=1
  - NPM_VERSION=2
  - NPM_VERSION=3
  - NPM_VERSION=4
  - NPM_VERSION=5
matrix:
  exclude:
    # Due to unsupported by Node.js 8 or later
    - node_js: 8
      env: NPM_VERSION=1
    - node_js: 9
      env: NPM_VERSION=1
    - node_js: 10
      env: NPM_VERSION=1
    - node_js: 11
      env: NPM_VERSION=1
    - node_js: 12
      env: NPM_VERSION=1
    - node_js: 13
      env: NPM_VERSION=1
