name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 8.x
            npm-version: 2
          - node-version: 8.x
            npm-version: 3
          - node-version: 10.x
            npm-version: 2
          - node-version: 10.x
            npm-version: 3
          - node-version: 10.x
            npm-version: 4
          - node-version: 10.x
            npm-version: 5
          - node-version: 10.x
            npm-version: 6
          - node-version: 12.x
            npm-version: 6
          - node-version: 14.x
            npm-version: 6
          - node-version: 14.x
            npm-version: 7
          - node-version: 15.x
            npm-version: 7

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install -g npm@${{ matrix.npm-version }}
          npm install
      - name: npm test
        run: |
          npm test
